### ISSUE TITLE
Track which CLI events were triggered by VS Code

### ISSUE THREAD

**Issue by jbyrum-stripe** [stripe/vscode-stripe#163]
In order to clearly track adoption of the CLI, we need to be able to filter out stripe CLI commands that were directly triggered by the VS Code extension.  

If a user executes a stripe CLI command in the VS Code terminal, this should NOT be excluded.

**Comment by etsai-stripe** [comment]
https://github.com/stripe/vscode-stripe/pull/398
the extension is no longer triggering CLI commands directly
