### ISSUE TITLE
Use smaller logo file in README

### ISSUE THREAD

**Issue by jhstrauss** [stripe/vscode-stripe#165]
It appears that when rendering the extension's README in the VS Code app, VS Code is ignoring the image width attribute in the README source. So the logo gets rendered full width and takes up the entire above the fold height on most screen sizes (see screenshot below). Presumably if the [logo file](https://github.com/stripe/vscode-stripe/blob/master/resources/logo.png) was smaller, then the README would render in the VS Code app the same way it does on the web. 

![Screen Shot 2021-02-05 at 4 37 12 PM](https://user-images.githubusercontent.com/391038/107103157-74c7a980-67d1-11eb-8393-4c7f8a9322d1.png)

**Comment by etsai-stripe** [comment]
![Screen Shot 2021-11-18 at 10 52 51 AM](https://user-images.githubusercontent.com/88805634/142478511-bedd3466-6b27-4e06-8656-6d6350732c2c.png)

issue has been fixed
