### ISSUE TITLE
Stripe VS Code Extension can't find Stripe CLI on M1 Mac

### ISSUE THREAD

**Issue by jhstrauss** [stripe/vscode-stripe#166]
## Issue
Running latest stable VS Code and Stripe Extension on M1 MacBook Air (see below for full version info), and the Stripe VS Code extension is unable to locate the Stripe CLI, which I can access via Terminal (see below screenshot).

![Screen Shot 2021-02-06 at 9 29 15 AM](https://user-images.githubusercontent.com/391038/107125441-f0bc0300-685e-11eb-96d0-64b6c60ac039.png)

I first installed the Stripe VS Code Extension before installing the Stripe CLI. I then used Homebrew to install the Stripe CLI via Terminal. But I continued to get the same error message in the Stripe VS Code Extension, even after quitting and relaunching VS Code and uninstalling and reinstalling the  Stripe VS Code Extension. 

I wonder if the issue could be that [Homebrew uses a different path](https://docs.brew.sh/Installation) on M1 Macs (/opt/homebrew) than on Intel Macs (/usr/local). Maybe the Stripe VS Code Extension isn't checking in the right place for the CLI files on M1 Macs. 

**Update:** I think this is the case, see: 
https://github.com/stripe/vscode-stripe/blob/60504a3ab1289fcf8bffabda41ef49aa4534a962/src/stripeClient.ts#L119-L136
 
### VS Code
Version: 1.53.0
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T16:01:04.046Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
### stripe.vscode-stripe
Version: 1.7.0
### OS
System Version: macOS 11.2 (20D64)
Hardware: MacBook Air (M1, 2020)

**Comment by jaredpalmer** [comment]
Same here.

**Comment by brad-richardson** [comment]
Thanks for figuring this out, I worked around it by adding a symlink: `sudo ln -s /opt/homebrew/bin/stripe /usr/local/bin/stripe`

**Comment by jhstrauss** [comment]
This should be fixed by #194
