### ISSUE TITLE
Bundle Extension

### ISSUE THREAD

**Issue by gracegoo-stripe** [stripe/vscode-stripe#193]
When packaging the extension we get this suggestion from VSCode:
```
This extension consists of 1530 files, out of which 847 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
```

**Comment by vcheung-stripe** [comment]
May resolve https://github.com/stripe/vscode-stripe/issues/167 as per https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load.

**Comment by vcheung-stripe** [comment]
Adding webpack regardless of #167; paired with @richardm-stripe.
