### ISSUE TITLE
BUG: Command 'Stripe: Start CLI' resulted in an error (command 'stripe.openCLI' not found)

### ISSUE THREAD

**Issue by darthzyklus** [stripe/vscode-stripe#201]
Hi there. I am on arch linux distro, I am preseting the following errors

Command 'Stripe: Start CLI' resulted in an error (command 'stripe.openCLI' not found)
Command 'Stripe: Login' resulted in an error (command 'stripe.login' not found)

I have the stripe cli installed on the following paths

/usr/bin/stripe
/usr/local/bin/stripe

Also, I downloaded this repo, install the dependencies and run the extension on debug mode and it works better. I can use the commands above, but  also those commands stripe.openCLI and stripe.login are undefined on the debug log output

**Comment by gracegoo-stripe** [comment]
Hi Andres, thanks for reporting this! Some questions to help us get started:
1. What version of the extension are you running? I assume the problem still persisted for you on the latest since you mentioned you downloaded the repo, but this still might help us narrow things down. 
2. When you run the extension regularly (not from the repo in debug mode), do you see any errors in the Console when you turn on Developer tools? (Help -> Toggle Developer Tools).

**Comment by darthzyklus** [comment]
@gracegoo-stripe 

1.  I installed first the 1.7.3 directly from the vscode editor then I try it with the repo and on debug mode and only works this way.

2. Errors using the dev tools
```
workbench.desktop.main.js:1786 [EQuimper.react-native-react-redux]: Unknown language in `contributes.react-native-react-redux.language`. Provided value: jsx
_logMessageInConsole @ workbench.desktop.main.js:1786
workbench.desktop.main.js:1786 [stripe.vscode-stripe]: Unknown language in `contributes.vscode-stripe.language`. Provided value: jsx

workbench.desktop.main.js:1786 Activating extension 'stripe.vscode-stripe' failed: Cannot find module './stripeTreeViewDataProvider'
Require stack:
- /home/andres/.vscode-insiders/extensions/stripe.vscode-stripe-1.7.3/out/stripeDashboardView.js
- /home/andres/.vscode-insiders/extensions/stripe.vscode-stripe-1.7.3/out/extension.js
- /opt/visual-studio-code-insiders/resources/app/out/vs/loader.js
- /opt/visual-studio-code-insiders/resources/app/out/bootstrap-amd.js
- /opt/visual-studio-code-insiders/resources/app/out/bootstrap-fork.js.

```

**Comment by gracegoo-stripe** [comment]
Thanks, Andre. Does the extension load at all for you? Do you see any content on the Stripe side bar, or see an error message like "Activating extension 'stripe.vscode-stripe' failed"? For reference, even if you're not logged in or able to use the CLI, you should still see things in side pane like links on "Dashboard" section of the page.

**Comment by darthzyklus** [comment]
@gracegoo-stripe 
No. I don't see any content at all. Just the sections titles but without any content inside.

**Comment by darthzyklus** [comment]
![image](https://user-images.githubusercontent.com/12199455/113336262-237cf780-92f4-11eb-90ec-ab8e32baeb4e.png)

**Comment by gracegoo-stripe** [comment]
The logs were super helpful, @vcheung-stripe realized that the extension can't find ./stripeTreeViewDataProvider because the file is under `stripe.vscode-stripe-1.7.3/out/StripeTreeViewDataProvider.js` with a capital S. We didn't notice this in our mac machines the fs is case insensitive. 

He also just released a [commit](https://github.com/stripe/vscode-stripe/commit/992008c0c60a1e9a871c11d77c67acedea51ab3f) that I think would address this issue. What was the most recent commit you had when you downloaded the repo and ran it in debug mode?

**Comment by darthzyklus** [comment]
I'm glad that logs helped. 


Sure, here is the last commit

commit 9eedcb701ec811e2258fad400835a69c72f7de88 (HEAD -> master, origin/master, origin/HEAD)
Author: gracegoo-stripe <75757829+gracegoo-stripe@users.noreply.github.com>
Date:   Wed Mar 31 15:06:42 2021 -0700

    Adding event streaming (#195)

**Comment by gracegoo-stripe** [comment]
Okay, that should have the commit we want. When you run the repo in debug mode are you still seeing the same error, or a different set of errors?

**Comment by darthzyklus** [comment]
@gracegoo-stripe 

Just a warning of deprecation, but no more errors at the dev tools and  the extensions works

```
Extension Host
/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2814 Debugger attached.
/opt/visual-studio-code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:62 [Extension Host] (node:25518) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (at writeOut (internal/process/warning.js:32:3))
```

Here I can see the content  and also I am able to use the stripe CLI features on debug mode.
![image](https://user-images.githubusercontent.com/12199455/113346147-790bd100-9301-11eb-87ce-11786303a753.png)

The only errors are displayed at the vscode when staring the debug mode:
![image](https://user-images.githubusercontent.com/12199455/113346270-9e98da80-9301-11eb-9aa0-683a69c20454.png)

**Comment by gracegoo-stripe** [comment]
Ah perfect! Let me make a release for you shortly so we can get your workspace working in non-dev mode!

**Comment by darthzyklus** [comment]
Great!  awesome, let me test.

**Comment by gracegoo-stripe** [comment]
The new version is now live in the marketplace! Version 1.7.4 is the one to look out for.

**Comment by darthzyklus** [comment]
@gracegoo-stripe 
Awesome. it is working thank you so much!

**Comment by gracegoo-stripe** [comment]
That's great! Thanks again for reporting the bug.
