### ISSUE TITLE
Add setting to opt-out of snippet autocomplete

### ISSUE THREAD

**Issue by jplhomer** [stripe/vscode-stripe#204]
I love this plugin! However, I rely on VSCode autocomplete a bunch to do automatic imports of e.g. PHP namespaced classes and dependencies.

Whenever I have a class that includes `str` or anything close to a domain model of a Stripe class, I get a long _long_ list of Stripe snippets before my own local suggestions.

Any way to disable this or reorder these?

https://user-images.githubusercontent.com/848147/113528521-6eae3900-9586-11eb-8ec3-e3ebc3887542.mov

Thanks!

**Comment by vcheung-stripe** [comment]
Hello @jplhomer, you can set `editor.snippetSuggestions` in your Visual Studio Code settings to reorder or hide snippets: https://code.visualstudio.com/docs/editor/intellisense#_snippets-in-suggestions. Please let me know if this helps!

**Comment by jplhomer** [comment]
@vcheung-stripe Wow thank you! TIL this is terrific.
