### ISSUE TITLE
"Update CLI" alert message needs to be updated

### ISSUE THREAD

**Issue by jbyrum-stripe** [stripe/vscode-stripe#216]
If user's CLI is outdated, we suggest that they update.

"We recommend being on at least v1.5.13 of the CLI for the best experience."

However, today's update link takes the user to the installation section of the documentation:
https://stripe.com/docs/stripe-cli#install

Suggest we either:

- Direct user to CLI documentation section that describes how to update CLI (which doesn't exist today, we'll have to write it).  
- Add a `stripe update` command to CLI, and reference that in both VS Code, as well as the CLI error message: "A newer version of the Stripe CLI is available, please update to: v1.5.14 by running `stripe update`"

cc: @pepin-stripe @tomer-stripe

**Comment by vcheung-stripe** [comment]
We could move content from this [wiki page](https://github.com/stripe/stripe-cli/wiki/Installing-and-updating#updating) into the [docs](https://stripe.com/docs/stripe-cli). We'll have to make changes because it's out of date.
