### ISSUE TITLE
API key linting false positive detects obscured keys from stripe error messages

### ISSUE THREAD

**Issue by focusaurus** [stripe/vscode-stripe#220]
I have some error handling unit tests where I have a copy of a JSON document returned from a stripe API call. The error message includes an API key redacted with `*******`, but the linter still thinks this is a security issue.

```json
// "message": "The provided key 'sk_test_9L****************************y9yo' does not......
```

As a workaround I'll probably extra-redact this but in general I like including full sample responses in comments alongside my code. There's no actual security issue here as the key is redacted.

What I'd like to see is the linter's key matching be precise enough to ignore redacted keys.

**Comment by gracegoo-stripe** [comment]
Yup good point, thanks for reporting the bug! We have addressed the issue with the linked PR.
