### ISSUE TITLE
This Stripe API Key is hardcoded. For better security, consider using a .env file.  See https://stripe.com/docs/keys#safe-keys for more advice.

### ISSUE THREAD

**Issue by dani3l3** [stripe/vscode-stripe#222]
This message/recommendation also triggers for my actual .env file, the key is NOT in the code. 
I guess those .env files should be excluded from the scan if the recommendation is to use them... it sounds rather stupid to be scolded because you should be doing something.... that you are actually already doing.
I am using this popular library to handle the .env configuration https://github.com/vlucas/phpdotenv

**Comment by gracegoo-stripe** [comment]
Thanks for reporting the bug @dani3l3! We've added logic to ignore .env files from being flagged by our linter in the PR above.
