### ISSUE TITLE
API Reference support for Java

### ISSUE THREAD

**Issue by jbyrum-stripe** [stripe/vscode-stripe#238]
Some methods in Java and all in .NET are called on a specific instance of an object. Because this object can be named anything, it makes creating a pattern to match on difficult. See Java and .Net snippets for this example: https://stripe.com/docs/api/credit_notes/lines.

We need to look for an alternative way of supporting the hover-over reference.

**Comment by etsai-stripe** [comment]
first java lang support version released in v2.0.7
