### ISSUE TITLE
Update Forward webhooks prompting UX

### ISSUE THREAD

**Issue by gracegoo-stripe** [stripe/vscode-stripe#248]
When the user opens up the forward webhooks dialogue, we prompt the user to enter in two addresses, the 2nd for connect. The message varies only slightly so it's easy for users to think their input got eaten. 

We need to update the UX to at least clarify this.

**Comment by jbyrum-stripe** [comment]
@gracegoo-stripe If we can't figure out something intuitive on our own, we can always ask @karolis-stripe for help

**Comment by ctrudeau-stripe** [comment]
<img width="927" alt="Screen Shot 2021-06-08 at 3 53 58 PM" src="https://user-images.githubusercontent.com/49962232/121267887-c2cce680-c871-11eb-8751-bafff73b9873.png">
<img width="982" alt="Screen Shot 2021-06-08 at 3 53 54 PM" src="https://user-images.githubusercontent.com/49962232/121267891-c3657d00-c871-11eb-9211-52b4d87e6681.png">


What do you think @jbyrum-stripe we can differentiate by using brackets like this? Given we want it to be upfront. 

I've updated the text to better match the dashboard text: 
<img width="1225" alt="Screen Shot 2021-06-08 at 3 53 09 PM" src="https://user-images.githubusercontent.com/49962232/121267841-aa5ccc00-c871-11eb-9780-5aa94d860b8b.png">

**Comment by ctrudeau-stripe** [comment]
Ah this is a limit of vscode. We don't have a way to label the input box as far as I know. We can only provide a description. For what it's worth this is how all interactions work with input boxes in VSCode. 

<img width="758" alt="Screen Shot 2021-06-08 at 4 39 44 PM" src="https://user-images.githubusercontent.com/49962232/121271281-32de6b00-c878-11eb-9fed-0396ee6167e9.png">

**Comment by ctrudeau-stripe** [comment]
<img width="439" alt="Screen Shot 2021-06-08 at 4 45 15 PM" src="https://user-images.githubusercontent.com/49962232/121271677-0414c480-c879-11eb-8a2b-94e6c81cc1da.png">

We can add a description like this it looks like. And put those titles in there.

**Comment by ctrudeau-stripe** [comment]
<img width="900" alt="Screen Shot 2021-06-08 at 5 08 07 PM" src="https://user-images.githubusercontent.com/49962232/121273003-1f350380-c87c-11eb-8b97-8b96fcbb75c5.png">

Potential option is to move to a "QuickPick" dialog. If the user hasn't put a URL before it'll show this this. If they have it will be pre-filled with what they had previously. We can then offer our suggested URL like before. Ptal? @jbyrum-stripe

**Comment by vcheung-stripe** [comment]
@ctrudeau-stripe Does the QuickPick allow arbitrary input? I'm not sure if it does.

**Comment by ctrudeau-stripe** [comment]
Ah yes. You are right that it doesn't accept arbitrary input. Looks like the only option is to not pre-fill with something recommended if the text below won't work.

**Comment by ctrudeau-stripe** [comment]
https://github.com/stripe/vscode-stripe/issues/248#issuecomment-857239528

@jbyrum-stripe will this solution suffice given it's our only option with the VSCode APIs without going completely custom?
