### ISSUE TITLE
Progress Indicator while cloning stripe samples

### ISSUE THREAD

**Issue by gracegoo-stripe** [stripe/vscode-stripe#251]
Add a progress indicator when the cloning happens so the user gets some feedback after they've went through the samples workflow. Right now the screen just disappears and the user needs to wait for a few seconds before the workspace opening prompt pops up.

**Comment by vcheung-stripe** [comment]
The progress indicator should be added somewhere here: https://github.com/stripe/vscode-stripe/pull/241/files#diff-a616251b82da1a5810330163f4c1ea7ab585905b04f6e9bf0b18f6fba86b1707R174

I think `vscode.window.showQuickPick` will show progress when a `Promise` is passed as the first argument.
