### ISSUE TITLE
Spinner for streaming looks frozen

### ISSUE THREAD

**Issue by gracegoo-stripe** [stripe/vscode-stripe#252]
The spinner for the logs and events streaming looks like it's frozen because it just displays one frame (or the same frame over and over again) until the streaming actually starts. Look into see if this is something we can fix.

**Comment by vcheung-stripe** [comment]
Here's how it's done in Azure extensions. It looks like they include a custom SVG: https://github.com/microsoft/vscode-azuretools/blob/6d242c5132c2d11b21e6d7d2e6cc6629aa2dbfa1/ui/src/tree/AzureAccountTreeItemBase.ts#L98

**Comment by vcheung-stripe** [comment]
Or better, looks like it can be done without a custom SVG: https://github.com/microsoft/vscode/issues/117859

**Comment by gracegoo-stripe** [comment]
The spinner looks wonky with the version of the vscode engine we have -- we'll need to update the min version of vscode

**Comment by gracegoo-stripe** [comment]
Actually, this update may not be out yet

**Comment by gracegoo-stripe** [comment]
So for now we can use a custom SVG or updating the padding ourselves for now -- I'll probably do the latter

**Comment by gracegoo-stripe** [comment]
Actually, I don't know if we can manipulate the css of the pane from our extension.. But, it looks like the expected release date that includes this update is expected to be on June 9th: https://github.com/microsoft/vscode/issues/125031. I'd say it's worth waiting for that.

**Comment by vcheung-stripe** [comment]
We can probably merge this now without waiting for the next VS Code update. Even if we wait, users on older VS Code versions will still see the wonky spinner.

**Comment by gracegoo-stripe** [comment]
You're right, I initially thought that if we upgrade the engine the user would get prompted to update their VSCode but it looks like it's the other way around and they don't get prompted for our extension upgrade unless they are on a newer version.

**Comment by vcheung-stripe** [comment]
Can this be closed?

**Comment by gracegoo-stripe** [comment]
Yup
