### ISSUE TITLE
Error while trying to add the stripe debugger configuration

### ISSUE THREAD

**Issue by gracegoo-stripe** [stripe/vscode-stripe#253]
![GbuxuT5A](https://user-images.githubusercontent.com/75757829/121052022-d17ea500-c76e-11eb-8fa0-d09249900a66.png)

**Comment by vcheung-stripe** [comment]
I think this can be fixed with a null check here:

https://github.com/stripe/vscode-stripe/pull/242/files#diff-ca92d1afe836a483259dfc56e55ada3e33076f195fd4f2e7a0fd06be4bfa664fR131

Change `if (options.skipVerify)` => `if (options?.skipVerify)`
