### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by gracegoo-stripe** [stripe/vscode-stripe#254]
Update official documentation with new features: https://stripe.com/docs/stripe-vscode

And README, if relevant.

**Comment by jbyrum-stripe** [comment]
@gracegoo-stripe Can we set a target date for these updates, so that I have a chance to review early next next week?

Jordan Merrick has offered to help with docs too!

**Comment by gracegoo-stripe** [comment]
Sure, we could set a goal of EOW, and we can always come back to update the assets if they change after the review.
