### ISSUE TITLE
No instances of MSBuild could be detected.

### ISSUE THREAD

**Issue by rainmanjam** [stripe/vscode-stripe#363]
Installed on a clean version of VSCode and Get the following output message. MSCode is installed and available from the terminal.

`Unhandled exception. System.InvalidOperationException: No instances of MSBuild could be detected.
Try calling RegisterInstance or RegisterMSBuildPath to manually register one.
   at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()
   at stripe.LanguageServer.Program.Main(String[] args) in /Users/gracegoo/stripe/vscode-stripe/src/stripeDotnetLanguageServer/stripe.LanguageServer/Program.cs:line 34
   at stripe.LanguageServer.Program.<Main>(String[] args)
[Error - 12:57:20 PM] Connection to server got closed. Server will not be restarted.
`
VSCode 1.60.0
MacOS 12.0 Beta

`❯ ./dotnet-core-uninstall list

This tool cannot uninstall versions of the runtime or SDK that are installed using zip/scripts. The versions that can be uninstalled with this tool are:

.NET Core SDKs:
  5.0.400  (x64)  [Used by Visual Studio for Mac. Specify individually or use —-force to remove]
  3.1.412  (x64)

.NET Core Runtimes:
  5.0.9   (x64)  [Used by Visual Studio for Mac or SDKs. Specify individually or use —-force to remove]
  3.1.18  (x64)  [Used by Visual Studio for Mac or SDKs. Specify individually or use —-force to remove]
  3.0.1   (x64)  [Used by Visual Studio for Mac or SDKs. Specify individually or use —-force to remove]
  2.1.23  (x64)  [Used by Visual Studio for Mac or SDKs. Specify individually or use —-force to remove]
 ~/dotnet-core-uninstall `

**Comment by lakishadavid** [comment]
I have the same problem.

My setup:
VS Code 1.60.1
Ubuntu-20.04
WSL2
stripe_1.7.3 (I have active products on Stripe Dashboard.)

I followed the video Stripe for Visual Studio Code published by Stripe for Developers on [YouTube](https://www.youtube.com/watch?v=fATvgUMWLzU). 
I received the success message after pairing, closed VS Code, opened VS Code, and then received the following error:

```
Unhandled exception. System.InvalidOperationException: No instances of MSBuild could be detected.
Try calling RegisterInstance or RegisterMSBuildPath to manually register one.
   at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()
   at stripe.LanguageServer.Program.Main(String[] args) in /Users/gracegoo/stripe/vscode-stripe/src/stripeDotnetLanguageServer/stripe.LanguageServer/Program.cs:line 34
   at stripe.LanguageServer.Program.<Main>(String[] args)
[Error - 3:42:59 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by etsai-stripe** [comment]
please install dotnet SDK core to try again

**Comment by rainmanjam** [comment]
Getting the same error after reinstalling dotnet SDK Core

`Unhandled exception. System.InvalidOperationException: No instances of MSBuild could be detected.
Try calling RegisterInstance or RegisterMSBuildPath to manually register one.
   at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()
   at stripe.LanguageServer.Program.Main(String[] args) in /Users/etsai/stripe/vscode-stripe/src/stripeDotnetLanguageServer/stripe.LanguageServer/Program.cs:line 33
   at stripe.LanguageServer.Program.<Main>(String[] args)
[Error - 12:22:45 AM] Connection to server got closed. Server will not be restarted.
`

**Comment by jdempcy** [comment]
I'm having this problem as well:

Unhandled exception. System.InvalidOperationException: No instances of MSBuild could be detected.
Try calling RegisterInstance or RegisterMSBuildPath to manually register one.
   at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()
   at stripe.LanguageServer.Program.Main(String[] args) in /Users/etsai/stripe/vscode-stripe/src/stripeDotnetLanguageServer/stripe.LanguageServer/Program.cs:line 33
   at stripe.LanguageServer.Program.<Main>(String[] args)
[Error - 10:18:56 AM] Connection to server got closed. Server will not be restarted.

This is just after installing the Stripe plugin for vscode on a fresh install, 2020 MacBook Pro running macOS Big Sur.

**Comment by jdempcy** [comment]
@etsai-stripe your comment to install SDK core and closing the issue does not seem to apply. I have the following SDKs instaled:

``` dotnet --list-sdks                                                              Sat Jan 22 09:08:03 2022
3.1.407 [/usr/local/share/dotnet/sdk]
3.1.408 [/usr/local/share/dotnet/sdk]
5.0.103 [/usr/local/share/dotnet/sdk]
5.0.200 [/usr/local/share/dotnet/sdk]
5.0.201 [/usr/local/share/dotnet/sdk]
5.0.202 [/usr/local/share/dotnet/sdk]```

Do I need another version?

**Comment by makinibryan** [comment]
Anyone who found a fix to this error
Building project ...
Scaffolding failed.
No instances of MSBuild could be detected.
Try calling RegisterInstance or RegisterMSBuildPath to manually register one.

**Comment by thismaker** [comment]
> Anyone who found a fix to this error Building project ... Scaffolding failed. No instances of MSBuild could be detected. Try calling RegisterInstance or RegisterMSBuildPath to manually register one.

I ran into the same error while trying to add Azure AD intergration to an AspNetCore, solution was to cd into the project directory and run `dotnet tool update microsoft.dotnet-msidentity`, you can check the id of the tool with 'dotnet tool list` in case it doesn't match mine, just in case.

**Comment by xjamiecarroll** [comment]
I encounted this by running the following code on the mslearn-secure-aspnet-core-identity learning project

`dotnet aspnet-codegenerator identity --useDefaultUI --dbContext DatabaseContext`

I only had dotnet 7 installed but that project was using:

<PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
</PropertyGroup>

All I had to do to make it work was change the target framework

`<TargetFramework>net6.0</TargetFramework>`
to
`<TargetFramework>net7.0</TargetFramework>`

Then when I ran my command

`dotnet aspnet-codegenerator identity --useDefaultUI --dbContext DatabaseContext`

and It worked.

➜  dotnet aspnet-codegenerator identity --useDefaultUI --dbContext DatabaseContext
Building project ...
Finding the generator 'identity'...
Running the generator 'identity'...
Modified C:\Users\jamie\Developer\new\mslearn-secure-aspnet-core-identity\RazorPagesPizza\Program.cs.

RunTime 00:00:14.17

**Comment by wsigel** [comment]
Just changing the target framework didn't do it for me. I also had to update the other 5 packages mentioned to version 7.0.4 / 7.0.5
Besides that I also had to install another nuget package: Microsoft.EntityFrameworkCore:Tools
After that I was able to build the mslearn-secure-aspnet-core-identity learning project
