### ISSUE TITLE
Add ability to expand logs request when listening

### ISSUE THREAD

**Issue by auchenberg-stripe** [stripe/vscode-stripe#39]
From BETA user:

> “Start API logs streaming” could be much more than a wrapper for `stripe logs tail`. It would be cool if I could expand each request to see its parameters.

**Comment by vcheung-stripe** [comment]
We should probably avoid showing more request logs data than what we currently display. There is a high risk of accidentally leaking PII if we show API request params and response bodies. I think a reasonable tradeoff would be to link to the dashboard like the CLI does, even though it's not the most seamless experience.

**Comment by vcheung-stripe** [comment]
Closing. We added links to the dashboard instead of showing logs inside the editor.
