### ISSUE TITLE
Stripe extension forces installation of Java extensions

### ISSUE THREAD

**Issue by auchenberg** [stripe/vscode-stripe#439]
I opened my VS Code after a while to discover that the Stripe Extension forcedly installed a range of Java Extensions for my editor. I'm not a Java developer, and now my editor is forcing me to configure my Java environment.

This is a sub optimal developer experience. My Stripe tooling shouldn't force a specific set of dependencies on me, but instead adopt to the environment it's in. 

This is the first time user experience when switching to the Stripe view in VS Code:

https://user-images.githubusercontent.com/173559/141697502-16d8ef0e-fe97-4125-bca4-68f672f00e2e.mov

**Error when trying to install the java extension pack:**

<img width="468" alt="Screen Shot 2021-11-14 at 12 24 12 PM" src="https://user-images.githubusercontent.com/173559/141697451-d024e856-42cc-4649-afed-725650a832a8.png">

**Comment by etsai-stripe** [comment]
@auchenberg this is a side effect of bundling different language server supports with the main extension (the same issue also happens with dotnet language support). we are exploring the possibility of building language specific extensions/add-ons. thank you for your feedback

**Comment by fishcharlie** [comment]
Glad I was able to figure this out. Will be uninstalling Stripe from VSCode until this is fixed (subscribed to the issue for updates). Absolutely awful UX currently.

Any workarounds would also be appreciated. I'm not a Java developer, so I'm not quite sure how to fix this and hesitant to download something **just** to make this one extension work.

**Comment by etsai-stripe** [comment]
@fishcharlie @auchenberg 
this should be fixed in v2.0.10

**Comment by fishcharlie** [comment]
@etsai-stripe Wow! From issue creation to fix in about 2 days. VERY impressive. Will try it out and report back if the issue persists.
