### ISSUE TITLE
Use welcome views for login and install screens

### ISSUE THREAD

**Issue by auchenberg-stripe** [stripe/vscode-stripe#57]
We should use the new welcome views to show install and login states instead of notfications.

![image](https://user-images.githubusercontent.com/53238203/83909602-f5537900-a71d-11ea-9ac8-a18444cd61b8.png)

![image](https://user-images.githubusercontent.com/53238203/83909781-43687c80-a71e-11ea-8809-346f45778b14.png)

Feature:https://code.visualstudio.com/api/extension-guides/tree-view#welcome-content
API: https://github.com/microsoft/vscode/issues/89080

**Comment by auchenberg-stripe** [comment]
API docs: https://code.visualstudio.com/api/references/contribution-points#contributes.viewsWelcome

**Comment by vcheung-stripe** [comment]
Here's a view I came up with. We hide the events and logs views until we can detect the CLI. There are buttons to read installation instructions or set a custom path. Once we detect that it's installed, the events and logs appear. What do folks think?

https://user-images.githubusercontent.com/71457708/117207257-9e7c7680-ada8-11eb-841a-348f35c2d55a.mov
