### ISSUE TITLE
API key expired error

### ISSUE THREAD

**Issue by DIGITALSQUAD** [stripe/vscode-stripe#673]
When selecting **Trigger new event** or **Forward events to your local machine**, raise an API expired error.
On Stripe CLI, API key option is available but I guess the API key is hard coded, and don't know how to pass API key on VS CODE.
```
 FATAL Error while authenticating with Stripe: Authorization failed, status=401, body={
  "error": {
    "code": "api_key_expired",
    "doc_url": "https://stripe.com/docs/error-codes/api-key-expired",
    "message": "Expired API Key provided: rk_test_*********************************************************************************************KtSz7X",
    "type": "invalid_request_error"
  }
}
```

**Comment by gracegoo-stripe** [comment]
Hi @DIGITALSQUAD, we don't have a way for you to pass in an API key for these actions from the extension. Could you login to your account? There should be a login flow that pops up but that seems to not be coming up for some reason -- I'll look into that. Meanwhile, you can login via the command line with `stripe login`. This will save the credentials for you so you do not have to provide the key for every command.

**Comment by DIGITALSQUAD** [comment]
@gracegoo-stripe Fixed after login, thanks!
