### ISSUE TITLE
As a user I can scaffold Stripe Samples from VS Code

### ISSUE THREAD

**Issue by auchenberg-stripe** [stripe/vscode-stripe#72]
As a user I can scaffold Stripe Samples from VS Code. 

Flow:
- "Create new project from Stripe Sample""
- User selects samples from list
- User selects their language
- Sample gets crated and opened in a new VS Code window.

**Comment by jbyrum-stripe** [comment]
@auchenberg-stripe Where do you think the "Create new project from Stripe Sample" link should live?  Did you envision this as a link in the "Help & Feedback" panel or as something a user can do from "File > New" (not sure if we can add menu items in VS Code)

**Comment by auchenberg-stripe** [comment]
We have a few options.

First I imagine us adding the command `Create new project from Stripe Sample` or `Start with Stripe Samples` which goes into the command palette in VS Code. Most commands in the editor don't have it's own UI, but are simple commands.

<img width="1552" alt="Screen Shot 2021-02-11 at 6 49 25 PM" src="https://user-images.githubusercontent.com/53238203/107783493-9cc38980-6d4a-11eb-9f10-bf28c9de6cd5.png">

After that we have the option to add specific UI for samples. Here we can go all in, and introduce a new "Samples" view where we could add toolbar icons like below, and use the view to show a list of recent samples, etc to promote them etc.

![image](https://user-images.githubusercontent.com/53238203/107783427-89b0b980-6d4a-11eb-83a9-2f340ade2675.png)

A simpler starting point could be to rename the `Dashboard` view to "Quick links" and add a "Start with Stripe Samples" button that invokes the command together with the 

![mokc](https://user-images.githubusercontent.com/53238203/107784463-c4ffb800-6d4b-11eb-843e-4a580f3a0c58.png)

**Comment by jbyrum-stripe** [comment]
Closing the loop on this, based on Slack discussions:

- Vincent investigated a sample browsing panel, and we both agreed that it wasn't a good UX.

Latest plan:
* Add link to "Start from Stripe Sample" to left nav
* Add item to "Create new project from Stripe Sample" to command palette
* Both link and item launch sample dialog

![Screen Shot 2021-02-16 at 10 50 47 AM](https://user-images.githubusercontent.com/76178996/108128456-99d5db00-7061-11eb-9b01-8be1d136983b.png)
